name: go code check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: go mod
        run: |
          find . -name "*.go" | xargs gofmt -w

          # exit with error if there are any changes
          if ! git diff --quiet; then git status; exit 1; fi

  go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: go mod
        run: |
          go mod tidy

          # check dirty
          if ! git diff --quiet; then git status; exit 1; fi

  go_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: go test
        run: |
          go test -v ./...

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
      - name: go-licenses
        run: |
          go install github.com/google/go-licenses@latest
          make license

          # check dirty
          if ! [[ -z "$(git status --porcelain licenses)" ]] || ! git diff --quiet; then git status; exit 1; fi
