name: CI for main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  version_tag:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: version
        id: version
        run: |
          version=$(head -n 1 < version.txt | tr -d '\n')
          echo "::set-output name=version::${version}"

      - name: tag check
        run: |
          if $(git fetch origin "refs/tags/v${{ steps.version.outputs.version }}"); then
            echo "${{ steps.version.outputs.version }} tag already exists!" >&2
            exit 1
          fi
